#!/usr/bin/env bun
/**
 * Install cursor-mem hooks + MCP at the user level (~/.cursor).
 * Isolated worker only. Never writes claude-mem-context.mdc. Never uses marketplace paths.
 */
import { existsSync, mkdirSync, readFileSync, unlinkSync, writeFileSync, chmodSync } from 'fs';
import { homedir } from 'os';
import { join } from 'path';
import { spawnSync } from 'child_process';
import {
  CURSOR_MEM_DATA_DIR,
  CURSOR_MEM_PORT,
  REPO_ROOT,
  WORKER_SCRIPT,
} from './cursor-mem-runtime.ts';

export const HOOK_SCRIPT_NAME = 'cursor-mem-hook.sh';
export const MCP_SERVER_NAME = 'cursor-mem';
export const SHORT_RULE_NAME = 'cursor-mem.mdc';
export const DUMP_RULE_NAME = 'claude-mem-context.mdc';
export const MARKETPLACE_MARKER = 'marketplaces/thedotmack';
export const ZSHRC_MARKER = '# cursor-mem agent preflight';

export const HOOK_EVENTS = [
  { event: 'sessionStart', workerEvent: 'ensure-start', timeout: 45 },
  { event: 'sessionStart', workerEvent: 'context', timeout: 15 },
  { event: 'beforeSubmitPrompt', workerEvent: 'session-init', timeout: 15 },
  { event: 'postToolUse', workerEvent: 'observation', timeout: 10 },
  { event: 'afterShellExecution', workerEvent: 'observation', timeout: 10 },
  { event: 'afterMCPExecution', workerEvent: 'observation', timeout: 10 },
  { event: 'afterFileEdit', workerEvent: 'file-edit', timeout: 10 },
  { event: 'stop', workerEvent: 'summarize', timeout: 10, loopLimit: null },
] as const;

export const SHORT_RULE = `---
alwaysApply: true
description: "How to use cursor-mem MCP search without dumping history"
---

# cursor-mem memory

You have MCP tools against the isolated cursor-mem worker (\`cursor-mem\`). Do not dump past sessions into the prompt. Unfold on demand.

## Tools

1. **search** — compact index (\`query\`, optional \`project\`, \`platformSource=cursor\`, \`limit\`)
2. **timeline** — context around an observation (\`anchor\` = ID)
3. **get_observations** — full details for filtered IDs only

## 3-layer workflow

1. Search first (~50–100 tokens/result)
2. Timeline around interesting IDs
3. Fetch details only for those IDs

Never call \`get_observations\` without filtering first. Prefer \`platformSource=cursor\`. Use the \`cursor-mem\` MCP server, not the marketplace \`plugin-claude-mem-mcp-search\`.
`;

export interface HookEntry {
  command: string;
  timeout?: number;
  loop_limit?: number | null;
}

export interface HooksJson {
  version: number;
  hooks: Record<string, HookEntry[]>;
}

export interface McpServerConfig {
  command: string;
  args?: string[];
  env?: Record<string, string>;
}

export interface McpJson {
  mcpServers: Record<string, McpServerConfig>;
}

export interface InstallLayout {
  cursorDir: string;
  repoRoot: string;
  dataDir: string;
  workerPort: string;
  zshrcPath?: string;
}

export function defaultLayout(): InstallLayout {
  return {
    cursorDir: join(homedir(), '.cursor'),
    repoRoot: REPO_ROOT,
    dataDir: CURSOR_MEM_DATA_DIR,
    workerPort: String(CURSOR_MEM_PORT),
    zshrcPath: join(homedir(), '.zshrc'),
  };
}

export function hookScriptPath(repoRoot: string): string {
  return join(repoRoot, 'scripts', HOOK_SCRIPT_NAME);
}

export function mcpServerPath(repoRoot: string): string {
  return join(repoRoot, 'plugin', 'scripts', 'mcp-server.cjs');
}

export function workerScriptPath(repoRoot: string): string {
  return join(repoRoot, 'plugin', 'scripts', 'worker-service.cjs');
}

export function agentBinDir(layout: InstallLayout): string {
  return join(layout.dataDir, 'bin');
}

export function agentWrapperPath(layout: InstallLayout): string {
  return join(agentBinDir(layout), 'agent');
}

export function shellenvPath(layout: InstallLayout): string {
  return join(layout.dataDir, 'shellenv.sh');
}

export function zshrcPath(layout: InstallLayout): string {
  return layout.zshrcPath ?? join(homedir(), '.zshrc');
}

export function resolveBunPath(): string {
  const which = spawnSync('bash', ['-lc', 'command -v bun'], { encoding: 'utf-8' });
  const fromPath = (which.stdout ?? '').trim();
  if (fromPath && existsSync(fromPath)) return fromPath;
  for (const candidate of [
    join(homedir(), '.bun', 'bin', 'bun'),
    '/usr/local/bin/bun',
    '/opt/homebrew/bin/bun',
  ]) {
    if (existsSync(candidate)) return candidate;
  }
  return 'bun';
}

export function buildShellenv(layout: InstallLayout): string {
  return `# Generated by cursor-mem. Puts the agent wrapper first on PATH so \`agent\` prints the viewer URL.\nexport PATH="${agentBinDir(layout)}:$PATH"\n`;
}

export function buildZshrcSnippet(layout: InstallLayout): string {
  return `${ZSHRC_MARKER}\n[ -f "${shellenvPath(layout)}" ] && . "${shellenvPath(layout)}"\n`;
}

export function buildAgentWrapper(layout: InstallLayout, bunPath = resolveBunPath()): string {
  const runtime = join(layout.repoRoot, 'scripts', 'cursor-mem-runtime.ts');
  const selfDir = agentBinDir(layout);
  return `#!/usr/bin/env bash
# Generated by cursor-mem. Prints the viewer URL, then execs Cursor's agent CLI.
set +e
"${bunPath}" "${runtime}" preflight
REAL=""
OLDIFS="$IFS"
IFS=:
for d in $PATH; do
  [ "$d" = "${selfDir}" ] && continue
  if [ -x "$d/agent" ]; then
    REAL="$d/agent"
    break
  fi
done
IFS="$OLDIFS"
if [ -z "$REAL" ]; then
  echo "cursor-mem: Cursor CLI 'agent' not found on PATH" >&2
  exit 127
fi
exec "$REAL" "$@"
`;
}

export function upsertZshrcSnippet(layout: InstallLayout): void {
  const path = zshrcPath(layout);
  const snippet = buildZshrcSnippet(layout);
  const existing = existsSync(path) ? readFileSync(path, 'utf-8') : '';
  if (existing.includes(ZSHRC_MARKER)) return;
  const next = existing.trimEnd() ? `${existing.replace(/\s+$/, '')}\n\n${snippet}` : snippet;
  writeFileSync(path, next.endsWith('\n') ? next : `${next}\n`, 'utf-8');
}

export function stripZshrcSnippet(text: string): string {
  const lines = text.split('\n');
  const kept: string[] = [];
  for (let i = 0; i < lines.length; i++) {
    if (lines[i].includes(ZSHRC_MARKER)) {
      const next = lines[i + 1] ?? '';
      if (next.includes('shellenv.sh')) i += 1;
      continue;
    }
    kept.push(lines[i]);
  }
  return kept.join('\n').replace(/\n{3,}/g, '\n\n');
}

export function userHookWrapperName(workerEvent: string): string {
  return `cursor-mem-${workerEvent}.sh`;
}

export function userHookWrapperRel(workerEvent: string): string {
  return `./hooks/${userHookWrapperName(workerEvent)}`;
}

export function userHooksDir(layout: InstallLayout): string {
  return join(layout.cursorDir, 'hooks');
}

export function userHookWrapperPath(layout: InstallLayout, workerEvent: string): string {
  return join(userHooksDir(layout), userHookWrapperName(workerEvent));
}

/** Cursor user hooks run from ~/.cursor; relative ./hooks/*.sh is the documented form. */
export function hookCommand(_repoRoot: string, workerEvent: string): string {
  return userHookWrapperRel(workerEvent);
}

export function buildUserHookWrapper(repoRoot: string, workerEvent: string): string {
  const trampoline = hookScriptPath(repoRoot);
  return `#!/usr/bin/env bash
# cursor-mem → isolated worker :37850 (not claude-mem :37777)
set +e
mkdir -p "$HOME/.cursor-mem"
printf '%s %s\\n' "$(date '+%Y-%m-%dT%H:%M:%S')" ${JSON.stringify(workerEvent)} >> "$HOME/.cursor-mem/hooks-fire.log" 2>/dev/null
exec /bin/bash ${JSON.stringify(trampoline)} ${JSON.stringify(workerEvent)}
`;
}

export function isCursorMemHook(command: string): boolean {
  return command.includes(HOOK_SCRIPT_NAME) || /(?:^|\/)hooks\/cursor-mem-/.test(command);
}

function hooksPath(layout: InstallLayout): string {
  return join(layout.cursorDir, 'hooks.json');
}

function mcpPath(layout: InstallLayout): string {
  return join(layout.cursorDir, 'mcp.json');
}

function rulesDir(layout: InstallLayout): string {
  return join(layout.cursorDir, 'rules');
}

function shortRulePath(layout: InstallLayout): string {
  return join(rulesDir(layout), SHORT_RULE_NAME);
}

function dumpRulePath(layout: InstallLayout): string {
  return join(rulesDir(layout), DUMP_RULE_NAME);
}

function readJsonFile<T>(path: string, fallback: T): T {
  if (!existsSync(path)) return fallback;
  const raw = readFileSync(path, 'utf-8');
  try {
    return JSON.parse(raw) as T;
  } catch {
    throw new Error(`Invalid JSON: ${path}`);
  }
}

function writeJsonFile(path: string, value: unknown): void {
  mkdirSync(join(path, '..'), { recursive: true });
  writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`, 'utf-8');
}

export function buildOurHookEntry(repoRoot: string, spec: (typeof HOOK_EVENTS)[number]): HookEntry {
  const entry: HookEntry = {
    command: hookCommand(repoRoot, spec.workerEvent),
    timeout: spec.timeout,
  };
  if ('loopLimit' in spec && spec.loopLimit !== undefined) {
    entry.loop_limit = spec.loopLimit;
  }
  return entry;
}

export function mergeHooks(existing: HooksJson | null, repoRoot: string): HooksJson {
  const hooks: Record<string, HookEntry[]> = { ...(existing?.hooks ?? {}) };
  const oursByEvent = new Map<string, HookEntry[]>();
  for (const spec of HOOK_EVENTS) {
    const list = oursByEvent.get(spec.event) ?? [];
    list.push(buildOurHookEntry(repoRoot, spec));
    oursByEvent.set(spec.event, list);
  }
  for (const [event, ourEntries] of oursByEvent) {
    const kept = (hooks[event] ?? []).filter((entry) => !isCursorMemHook(entry.command ?? ''));
    hooks[event] = [...kept, ...ourEntries];
  }
  return { version: existing?.version ?? 1, hooks };
}

export function stripOurHooks(existing: HooksJson): HooksJson {
  const hooks: Record<string, HookEntry[]> = {};
  for (const [event, entries] of Object.entries(existing.hooks ?? {})) {
    const kept = entries.filter((entry) => !isCursorMemHook(entry.command ?? ''));
    if (kept.length > 0) hooks[event] = kept;
  }
  return { version: existing.version ?? 1, hooks };
}

export function buildMcpServer(layout: InstallLayout): McpServerConfig {
  return {
    command: 'node',
    args: [mcpServerPath(layout.repoRoot)],
    env: {
      CLAUDE_MEM_DATA_DIR: layout.dataDir,
      CLAUDE_MEM_WORKER_PORT: layout.workerPort,
      CLAUDE_MEM_WORKER_SCRIPT_PATH: workerScriptPath(layout.repoRoot),
    },
  };
}

export function mergeMcp(existing: McpJson | null, layout: InstallLayout): McpJson {
  const mcpServers = { ...(existing?.mcpServers ?? {}) };
  mcpServers[MCP_SERVER_NAME] = buildMcpServer(layout);
  return { mcpServers };
}

export function stripOurMcp(existing: McpJson): McpJson {
  const mcpServers = { ...(existing.mcpServers ?? {}) };
  delete mcpServers[MCP_SERVER_NAME];
  return { mcpServers };
}

export interface InstallResult {
  hooksPath: string;
  mcpPath: string;
  rulePath: string;
  wrapperPath: string;
  shellenvPath: string;
}

export function installUserCursorMem(layout: InstallLayout = defaultLayout()): InstallResult {
  const trampoline = hookScriptPath(layout.repoRoot);
  if (!existsSync(trampoline)) {
    throw new Error(`Hook trampoline missing: ${trampoline}`);
  }
  const mcp = mcpServerPath(layout.repoRoot);
  if (!existsSync(mcp)) {
    throw new Error(`MCP server missing: ${mcp}`);
  }
  const worker = workerScriptPath(layout.repoRoot);
  if (!existsSync(worker)) {
    throw new Error(`Worker script missing: ${worker}`);
  }

  mkdirSync(layout.cursorDir, { recursive: true });
  mkdirSync(userHooksDir(layout), { recursive: true });
  const writtenEvents = new Set<string>();
  for (const spec of HOOK_EVENTS) {
    if (writtenEvents.has(spec.workerEvent)) continue;
    writtenEvents.add(spec.workerEvent);
    const wrapperPath = userHookWrapperPath(layout, spec.workerEvent);
    writeFileSync(wrapperPath, buildUserHookWrapper(layout.repoRoot, spec.workerEvent), 'utf-8');
    chmodSync(wrapperPath, 0o755);
  }

  const prevHooks = existsSync(hooksPath(layout))
    ? readJsonFile<HooksJson>(hooksPath(layout), { version: 1, hooks: {} })
    : null;
  writeJsonFile(hooksPath(layout), mergeHooks(prevHooks, layout.repoRoot));

  const prevMcp = existsSync(mcpPath(layout))
    ? readJsonFile<McpJson>(mcpPath(layout), { mcpServers: {} })
    : null;
  writeJsonFile(mcpPath(layout), mergeMcp(prevMcp, layout));

  mkdirSync(rulesDir(layout), { recursive: true });
  writeFileSync(shortRulePath(layout), SHORT_RULE, 'utf-8');

  mkdirSync(agentBinDir(layout), { recursive: true });
  writeFileSync(agentWrapperPath(layout), buildAgentWrapper(layout), 'utf-8');
  chmodSync(agentWrapperPath(layout), 0o755);
  writeFileSync(shellenvPath(layout), buildShellenv(layout), 'utf-8');
  upsertZshrcSnippet(layout);

  return {
    hooksPath: hooksPath(layout),
    mcpPath: mcpPath(layout),
    rulePath: shortRulePath(layout),
    wrapperPath: agentWrapperPath(layout),
    shellenvPath: shellenvPath(layout),
  };
}

export interface UninstallResult {
  hooksPath: string;
  mcpPath: string;
  removedRule: boolean;
  leftDumpUntouched: boolean;
}

export function uninstallUserCursorMem(layout: InstallLayout = defaultLayout()): UninstallResult {
  const hPath = hooksPath(layout);
  if (existsSync(hPath)) {
    const next = stripOurHooks(readJsonFile<HooksJson>(hPath, { version: 1, hooks: {} }));
    if (Object.keys(next.hooks).length === 0) {
      unlinkSync(hPath);
    } else {
      writeJsonFile(hPath, next);
    }
  }

  const mPath = mcpPath(layout);
  if (existsSync(mPath)) {
    const next = stripOurMcp(readJsonFile<McpJson>(mPath, { mcpServers: {} }));
    if (Object.keys(next.mcpServers).length === 0) {
      unlinkSync(mPath);
    } else {
      writeJsonFile(mPath, next);
    }
  }

  const rPath = shortRulePath(layout);
  let removedRule = false;
  if (existsSync(rPath)) {
    unlinkSync(rPath);
    removedRule = true;
  }

  const writtenEvents = new Set<string>();
  for (const spec of HOOK_EVENTS) {
    if (writtenEvents.has(spec.workerEvent)) continue;
    writtenEvents.add(spec.workerEvent);
    const wrapperPath = userHookWrapperPath(layout, spec.workerEvent);
    if (existsSync(wrapperPath)) unlinkSync(wrapperPath);
  }

  for (const extra of [agentWrapperPath(layout), shellenvPath(layout)]) {
    if (existsSync(extra)) unlinkSync(extra);
  }

  const zPath = zshrcPath(layout);
  if (existsSync(zPath)) {
    const next = stripZshrcSnippet(readFileSync(zPath, 'utf-8'));
    writeFileSync(zPath, next.endsWith('\n') || next === '' ? next : `${next}\n`, 'utf-8');
  }

  return {
    hooksPath: hPath,
    mcpPath: mPath,
    removedRule,
    leftDumpUntouched: existsSync(dumpRulePath(layout)),
  };
}

export interface InstallCheck {
  ok: boolean;
  errors: string[];
  warnings: string[];
  hooksPath: string;
  mcpPath: string;
  rulePath: string;
}

export function checkUserCursorMem(layout: InstallLayout = defaultLayout()): InstallCheck {
  const errors: string[] = [];
  const warnings: string[] = [];
  const hPath = hooksPath(layout);
  const mPath = mcpPath(layout);
  const rPath = shortRulePath(layout);

  if (!existsSync(hPath)) {
    errors.push(`missing ${hPath} — run npm run cursormem:install`);
  } else {
    const hooks = readJsonFile<HooksJson>(hPath, { version: 1, hooks: {} });
    const trampoline = hookScriptPath(layout.repoRoot);
    for (const spec of HOOK_EVENTS) {
      const entries = hooks.hooks?.[spec.event] ?? [];
      const expected = userHookWrapperRel(spec.workerEvent);
      const ours = entries.find(
        (entry) =>
          isCursorMemHook(entry.command ?? '') &&
          ((entry.command ?? '') === expected || (entry.command ?? '').includes(` ${spec.workerEvent}`)),
      );
      if (!ours) {
        errors.push(`hooks.${spec.event} missing cursor-mem ${spec.workerEvent}`);
        continue;
      }
      if (ours.command !== expected && !ours.command.includes(trampoline)) {
        errors.push(`hooks.${spec.event} ${spec.workerEvent} is not ${expected}`);
      }
      const wrapperPath = userHookWrapperPath(layout, spec.workerEvent);
      if (!existsSync(wrapperPath)) {
        errors.push(`missing wrapper ${wrapperPath}`);
      }
    }
  }

  if (!existsSync(mPath)) {
    errors.push(`missing ${mPath} — run npm run cursormem:install`);
  } else {
    const mcp = readJsonFile<McpJson>(mPath, { mcpServers: {} });
    const server = mcp.mcpServers?.[MCP_SERVER_NAME];
    if (!server) {
      errors.push(`mcp.json missing server "${MCP_SERVER_NAME}"`);
    } else {
      const raw = JSON.stringify(server);
      if (raw.includes(MARKETPLACE_MARKER)) {
        errors.push(`mcp "${MCP_SERVER_NAME}" points at marketplace (${MARKETPLACE_MARKER})`);
      }
      const args = server.args?.join(' ') ?? '';
      if (!args.includes(mcpServerPath(layout.repoRoot))) {
        errors.push(`mcp "${MCP_SERVER_NAME}" args are not this checkout's mcp-server.cjs`);
      }
      if (server.env?.CLAUDE_MEM_DATA_DIR !== layout.dataDir) {
        errors.push(`mcp env CLAUDE_MEM_DATA_DIR expected ${layout.dataDir}`);
      }
      if (server.env?.CLAUDE_MEM_WORKER_PORT !== layout.workerPort) {
        errors.push(`mcp env CLAUDE_MEM_WORKER_PORT expected ${layout.workerPort}`);
      }
      if (server.env?.CLAUDE_MEM_WORKER_SCRIPT_PATH !== workerScriptPath(layout.repoRoot)) {
        errors.push('mcp env CLAUDE_MEM_WORKER_SCRIPT_PATH is not this checkout worker-service.cjs');
      }
    }
  }

  if (!existsSync(rPath)) {
    errors.push(`missing short rule ${rPath}`);
  } else {
    const text = readFileSync(rPath, 'utf-8');
    if (text.includes('Memory Context from Past Sessions') || text.includes('auto-updated')) {
      errors.push(`${rPath} looks like a history dump, not the short tool rule`);
    }
  }

  if (existsSync(dumpRulePath(layout))) {
    warnings.push(`dump rule present (not ours to delete): ${dumpRulePath(layout)}`);
  }

  if (!existsSync(agentWrapperPath(layout))) {
    errors.push(`missing agent wrapper ${agentWrapperPath(layout)}`);
  } else {
    const wrapper = readFileSync(agentWrapperPath(layout), 'utf-8');
    if (!wrapper.includes('preflight') || !wrapper.includes('exec')) {
      errors.push(`agent wrapper ${agentWrapperPath(layout)} is not the cursor-mem launcher`);
    }
  }
  if (!existsSync(shellenvPath(layout))) {
    errors.push(`missing ${shellenvPath(layout)}`);
  }

  const projectHooks = join(process.cwd(), '.cursor', 'hooks.json');
  if (existsSync(projectHooks)) {
    try {
      const text = readFileSync(projectHooks, 'utf-8');
      if (text.includes(HOOK_SCRIPT_NAME)) {
        warnings.push(
          `project ${projectHooks} also has ${HOOK_SCRIPT_NAME} — Cursor will double-fire; remove project hooks`,
        );
      }
    } catch {
      // ignore unreadable project hooks
    }
  }

  return { ok: errors.length === 0, errors, warnings, hooksPath: hPath, mcpPath: mPath, rulePath: rPath };
}

function printCheck(check: InstallCheck): void {
  console.log(`hooks: ${check.hooksPath}`);
  console.log(`mcp:   ${check.mcpPath}`);
  console.log(`rule:  ${check.rulePath}`);
  for (const warning of check.warnings) {
    console.error(`warn: ${warning}`);
  }
  if (check.ok) {
    console.log('ok: user-level cursor-mem install');
    return;
  }
  for (const error of check.errors) {
    console.error(`error: ${error}`);
  }
}

function printUsage(): void {
  console.error('Usage: bun scripts/cursor-mem-install.ts install|uninstall|status');
}

function runCli(command: string): number {
  const layout = defaultLayout();
  if (command === 'install') {
    const result = installUserCursorMem(layout);
    console.log(`Installed cursor-mem user hooks → ${result.hooksPath}`);
    console.log(`Installed cursor-mem MCP       → ${result.mcpPath}`);
    console.log(`Short rule (no dump)           → ${result.rulePath}`);
    console.log(`Agent wrapper                  → ${result.wrapperPath}`);
    console.log(`Shell PATH snippet             → ${result.shellenvPath}`);
    console.log('Abre una terminal nueva (o: source ~/.cursor-mem/shellenv.sh).');
    console.log('Luego `agent` imprime cursor-mem started + http://localhost:37850 y arranca Cursor CLI.');
    const check = checkUserCursorMem(layout);
    printCheck(check);
    return check.ok ? 0 : 1;
  }
  if (command === 'uninstall') {
    const result = uninstallUserCursorMem(layout);
    console.log(`Removed cursor-mem hook entries from ${result.hooksPath}`);
    console.log(`Removed MCP server "${MCP_SERVER_NAME}" from ${result.mcpPath}`);
    if (result.removedRule) {
      console.log(`Removed ${join(layout.cursorDir, 'rules', SHORT_RULE_NAME)}`);
    }
    if (result.leftDumpUntouched) {
      console.log(`Left ${DUMP_RULE_NAME} untouched`);
    }
    return 0;
  }
  if (command === 'status') {
    const check = checkUserCursorMem(layout);
    printCheck(check);
    return check.ok ? 0 : 1;
  }
  printUsage();
  return 1;
}

if (import.meta.main) {
  const command = process.argv[2];
  if (!command) {
    printUsage();
    process.exit(1);
  }
  try {
    process.exit(runCli(command));
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : String(error);
    console.error(message);
    process.exit(1);
  }
}
